### PR TITLE
fix/enhancement: BalanceComponent not crashing and loading skeletons

### LINKED ISSUE #166: Balance component shows 0 as balance when still loading
Might be better to either show a placeholder or a loading animation to indicate to the user that their balance is still being fetched. If somehow something is not working, it will show 0 euros.

image

### LINKED ISSUE #170: Topping up with a negative amount causes the component to crash
If you type "-10" in the top up field, the component crashes.

image

### PR DESCRIPTION
**Pull request by CodeNamedRobin**
Fixes #170 
Fixes #166 
Also, for future reference, Dinero does not like it when any non integer is given (1005.0000001 is not allowed)

### CODE REVIEW

File: src/components/BalanceWithTopupComponent.vue [hunk 1]
```diff
@@ -20,14 +32,27 @@
...
+              currency="EUR"
+              locale="nl-NL"
+              :placeholder="$t('balance.Price')"
+              :min="0.0"
+              :min-fraction-digits="0"
+              :max-fraction-digits="2"
+              v-model="topupAmount"
+              inputId="amount"
+              @input="
+                (test) => {
```
Comment (SuperVK) [inline src/components/BalanceWithTopupComponent.vue]: maybe nice to actually change the "test" variable I once introduced when testing but never changed to "value" or smth

**Review by SuperVK — APPROVED** [review]
LGTM!

File: src/components/BalanceWithTopupComponent.vue (hunk 1 above)
Comment (CodeNamedRobin) [reply src/components/BalanceWithTopupComponent.vue]: Fixed, named to data
