### PR TITLE
fix(pos): incorrect remaining balance displayed

### LINKED ISSUE #432: [Bug]: Incorrect credit/debit after purchase displayed when charging different user
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Point of sale

### Current behaviour

Recently, when purchasing something on the POS on behalf of someone else, I noticed that the credit after purchase was displayed incorrectly. It displayed my balance with the purchase amount subtracted from it, rather than the new balance of the person actually paying.

Currently, at the bottom of the cart, the following is displayed:
image

When you change the user that is being charged, the debit/credit after purchase stays the same:
test

I have noticed that a request is sent to the `/v1/balances/{userId}` endpoint that is answered by a `403 Unauthorized` response.
I suspect this has something to do with the fact that not everyone is allowed to request a users balance (?)

### Desired behaviour

I expect the correct new balance to be displayed when making a purchase.

I understand that this might a privacy concern since you will be able to see everyone's balance, so it might be better to not display the credit/debit after purchase as soon as you are not purchasing something for yourself.

### Steps to reproduce

1. Log into the POS
2. Change who the order is for

(See GIF above)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by RubenLWF**
# Description

Removes the "Debit after purchase:" display if no value is returned by the API.
Also makes it so transaction history is not displayed when making a transaction for someone else.

## Related issues/external references

https://github.com/GEWIS/sudosos-frontend/issues/432

## Types of changes

- Bug fix _(non-breaking change which fixes an issue)_

### CODE REVIEW

File: apps/point-of-sale/src/components/Cart/CartComponent.vue [hunk 1]
```diff
@@ -68,7 +68,7 @@ const transactions = ref<BaseTransactionResponse[]>([]);
 
 const getUserRecentTransactions = () => {
   transactions.value = [];
-  if (cartStore.getBuyer) {
+  if (cartStore.getBuyer && cartStore.getBuyer.id === authStore.getUser?.id) {
```
Comment (RubenLWF) [inline apps/point-of-sale/src/components/Cart/CartComponent.vue]: Do the recent transaction for a user need to be displayed in borrelmode?

File: apps/point-of-sale/src/components/Cart/TransactionHistory/TransactionHistoryComponent.vue [hunk 2]
```diff
@@ -8,7 +8,7 @@
 */
 <template>
   <div class="flex-column h-full gap-2 mt-2 overflow-y-auto">
-    <h class="font-medium text-xl">Recent Purchases:</h>
+    <h1 class="font-medium text-xl" v-if="transactions.length > 0">Recent Purchases:</h1>
```
Comment (RubenLWF) [inline apps/point-of-sale/src/components/Cart/TransactionHistory/TransactionHistoryComponent.vue:11]: This is so "Recent Purchases:" is not rendered if the list of transactions is empty

File: apps/point-of-sale/src/stores/cart.store.ts [hunk 3]
```diff
@@ -57,7 +57,7 @@ export const useCartStore = defineStore('cart', {
     async setBuyer(buyer: BaseUserResponse | null) {
       this.buyer = buyer;
       if (buyer) {
-        const response = await apiService.balance.getBalanceId(buyer.id);
+        const response = await apiService.balance.getBalanceId(buyer.id).catch(this.buyerBalance = null);
```
Comment (RubenLWF) [inline apps/point-of-sale/src/stores/cart.store.ts:60]: If somewhere in this process an error occurs (like when a user to not have permission to get another users balance), the value is set to null, so no balance is rendered.

File: apps/point-of-sale/src/components/Cart/CartComponent.vue (hunk 1 above)
Comment (JustSamuel) [reply apps/point-of-sale/src/components/Cart/CartComponent.vue]: Yes, this is used when a BAC'er forgets if they entered a transaction or not.

**Review by JustSamuel — APPROVED** [review]

**Comment by JustSamuel** [comment]
Also @RubenLWF note that you should be able to create a branch directly on `sudosos-frontend`, meaning you won't have to wait for someone to approve the running of the checks.

**Comment by RubenLWF** [comment]
> Also @RubenLWF note that you should be able to create a branch directly on `sudosos-frontend`, meaning you won't have to wait for someone to approve the running of the checks.

I tried this but as soon as I tried to publish my branch I was told that I did not have write access for this repo :(

**Comment by JustSamuel** [comment]
> I tried this but as soon as I tried to publish my branch I was told that I did not have write access for this repo :(

Thanks for the heads-up, I'll look into it.

**Review by JustSamuel — APPROVED** [review]
